### ISSUE TITLE
Hope to support bidirectional link redirection and image embedding display

### ISSUE THREAD

**Issue by WinHex89** [hotoo/obsidian-markline#14]
![image](https://github.com/hotoo/obsidian-markline/assets/134070684/f2ec8b4b-8c00-4727-8683-833f774e646a)
What is slightly disappointing 🥹is that Markline can only redirect website links now, and other links are not supported😭. I hope Markline can be more powerful💪.
Also, is there any other way for me to contact with you, such as QQ or WeChat🥹

**Comment by hotoo** [comment]
get, I will do this feature as soon as possible.

**Comment by WinHex89** [comment]
May I ask if the latest version supports this feature

**Comment by hotoo** [comment]
@WinHex89 1.2.2

**Comment by WinHex89** [comment]
Furthermore, can it support a small window preview when the mouse hovers over the link
