### ISSUE TITLE
FR: Image and link improvements

### ISSUE THREAD

**Issue by javiavid** [hotoo/obsidian-markline#6]
I propose some improvements for image and URL support.

Images
- Support for local vault images
- Image display: instead of the image icon, a thumbnail of the image
- Display when hovering the mouse: If the above is not possible or if you want to keep the timeline cleaner, another option could be to hover the mouse over the icon and have the image displayed.

Urls
- Maximum number of characters in URLs: Sometimes URLs are very long and take up a lot of space in the timeline.
- Favicon to identify the origin: Something similar to what the obsidian plugin does https://github.com/joethei/obsidian-link-favicon (Maybe you can talk to the plugin author to make it compatible with your plugin)

**Comment by hotoo** [comment]
> Maximum number of characters in URLs: Sometimes URLs are very long and take up a lot of space in the timeline.

You can use `[link](url)`

**Comment by hotoo** [comment]
fixed by #11
