### ISSUE TITLE
FR: Colors

### ISSUE THREAD

**Issue by javiavid** [hotoo/obsidian-markline#7]
It would be great to be able to add colors to the background of the groups and to the dates. Something similar to markwhen.

<img width="710" alt="image" src="https://github.com/hotoo/obsidian-markline/assets/7627504/34427f9c-c2ff-4d3a-84fe-ce6018ca7e3e">

If the background is complicated to implement, at least being able to change the colors would help a lot.

**Comment by hotoo** [comment]
I have same idea like this.

**Comment by javiavid** [comment]
Here you have a demo, I think there are some interesting ideas.
https://meridiem.markwhen.com/rob/wedding
